### ISSUE TITLE
Minor nit - I don't think bool is actually serializable in current P4_16 spec

### ISSUE THREAD

**Issue by jafingerhut** [akeep/p4-proposals#1]
Summary: I believe that bool is currently in the same boat as enum as far as serializability goes, with 0 distinctions in what you can do with them.

This comment is prompted by this sentence in Section 3 of the serializable types proposal: "Currently, some scalar types (like bool types) are not explicitly serializable unless they are included as part of a header in the current spec"

bool is defined to have a way to cast a value of that type to bit<1>, or from bit<1> to bool.

Including either of them in a header is an error for the latest p4test and p4c-bm2-ss open source compilers.

I believe it is not allowed by the P4_16 v1.0.0 spec, either.

**Comment by akeep** [comment]
Yes, this certainly currently true.  I propose that like enums, which I
propose extending to include a serializable option for, we may want to
include a bool as serializable for similar reasons.  Unlike an enum though,
bool already has a natural (because the language provides an explicit cast
for this) backing type and representation.

That is really the only distinction I would make.

-andy:)



On November 13, 2017 at 4:45:08 PM, Andy Fingerhut (notifications@github.com)
wrote:

Summary: I believe that bool is currently in the same boat as enum as far
as serializability goes, with 0 distinctions in what you can do with them.

This comment is prompted by this sentence in Section 3 of the serializable
types proposal: "Currently, some scalar types (like bool types) are not
explicitly serializable unless they are included as part of a header in the
current spec"

bool is defined to have a way to cast a value of that type to bit<1>, or
from bit<1> to bool.

Including either of them in a header is an error for the latest p4test and
p4c-bm2-ss open source compilers.

I believe it is not allowed by the P4_16 v1.0.0 spec, either.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/akeep/p4-proposals/issues/1>, or mute the thread

**Comment by jafingerhut** [comment]
Yes, the difference between bool and enum is that I don't think anyone would ever want to define a different conversion between bool and `bit<W>` other than the obvious one between bool and `bit<1>`.

Closing this issue (feel free to reopen if there is any use in keeping it open).
