### ISSUE TITLE
Related p4c and p4-spec issues about converting enum to/from bit-vector types

### ISSUE THREAD

**Issue by jafingerhut** [akeep/p4-proposals#2]
I don't know how far any progress might be on this issue, but wanted to leave a pointer to it on this repo's issue, for reference.

https://github.com/p4lang/p4-spec/issues/394

**Comment by akeep** [comment]
A good link, I believe the proposal for handling enums is inline with
Mihai's final note that one must: choose a bit width (a backing type) and a
representation for each enum value.  Though it does not discuss what to do,
or how to handle the case where the user has specified more than one enum
item with the same value.

-andy:)



On November 13, 2017 at 4:47:53 PM, Andy Fingerhut (notifications@github.com)
wrote:

I don't know how far any progress might be on this issue, but wanted to
leave a pointer to it on this repo's issue, for reference.

p4lang/p4-spec#394 <https://github.com/p4lang/p4-spec/issues/394>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/akeep/p4-proposals/issues/2>, or mute the thread

**Comment by jafingerhut** [comment]
Closing this issue, since the issue I linked is now part of the document.
